### ISSUE TITLE
Não é possível adicionar métodos nas classes DAO no modelo de persistência

### ISSUE THREAD

**Issue by alanvieira16** [nemo-ufes/FrameWeb#2]
Ao arrastar DAO Method até a classe DAO, nada acontece

**Comment by nilber** [comment]
Final de semana eu mandei uma mensagem para o Silas avisando, também tive o mesmo problema.

Eu adicionei a TAG XML manualmente, assim ele apareceu no Editor e consegui editar.

**Comment by lucasrms** [comment]
Corrigido :)
