### ISSUE TITLE
Views não admitem herança

### ISSUE THREAD

**Issue by adlerosn** [nemo-ufes/FrameWeb#20]
Herança entre templates ou páginas, algo comum, não é representavel nos modelos de navegação.

Definir espaços com `ui:insert`, referenciar o template base no `ui:composition` e definir o conteúdo dos espaços com `ui:define` é algo recorrente. Com Django e Jinja2, `{% extends ... %}`, `{% block ... %}` e `{% endblock %}` são construções equivalentes.

Adicionar tal relação entre os elementos do pacote de visão permitiria reduzir a quantidade de relações entre elementos em alguns casos.

**Comment by vitorsouza** [comment]
Precisa ser estudado primeiro o que significaria esta herança e se isso é comum entre os frameworks controladores frontais. Acredito que devamos esperar a análise ontológica deste tipo de framework antes de fazer uma mudança deste nível.
