### ISSUE TITLE
Adicionar Template com erro

### ISSUE THREAD

**Issue by ggnogueira** [nemo-ufes/FrameWeb#4]
Ao tentar adicionar um template no modelo de navegação o nome do pacote é alterado. Com isso, não é possível colocar no diagrama o <<template>>.

**Comment by adlerosn** [comment]
Este erro me afeta. Como reproduzir:
- Crie um `View Package`
- Arraste um `Template` para o `View Package` esperando ver uma classe com o estereótipo `<<template>>`
- Veja o nome do seu pacote ser alterado e "New Template" e nenhuma classe estereotipada ser criada em seu modelo.

**Comment by vitorsouza** [comment]
Eu acho que deveríamos remover o tipo de element _template_ do metamodelo de FrameWeb ou, no mínimo, retirá-lo da paleta do editor. Templates eram específicos do Struts2 e não existem no JSF por exemplo. Até que alguém faça uma análise ontológica de frameworks controlador frontal, é melhor trabalharmos apenas com o conceito de página. Alguém que use Struts2 poderia criar páginas com o sufixo `.ftl` para arquivos FreeMarker e vai funcionar tudo igual.

**Comment by vitorsouza** [comment]
Resolvedo a issue #19, resolve esta também, com a solução que propus: remover os templates.
